#!/usr/bin/env python3
"""
TUI Installer for VPN Bot
Text-based User Interface for easy installation and configuration
"""

import curses
import os
import sys
import subprocess
from pathlib import Path

class Installer:
    def __init__(self):
        self.stdscr = None
        self.current_field = 0
        self.fields = [
            ('Panel URL', 'PANEL_URL', 'https://your-panel-url'),
            ('Panel Username', 'PANEL_USERNAME', 'admin'),
            ('Panel Password', 'PANEL_PASSWORD', ''),
            ('Panel Proxy (optional)', 'PANEL_PROXY', ''),
            ('Telegram Bot Token', 'TELEGRAM_BOT_TOKEN', ''),
            ('Telegram Proxy (optional)', 'TELEGRAM_PROXY', ''),
            ('Inbound ID', 'INBOUND_ID', '1'),
            ('Payment Gateway', 'PAYMENT_GATEWAY', 'zarinpal'),
            ('Zarinpal Merchant ID', 'ZARINPAL_MERCHANT_ID', ''),
            ('Pay.ir API Key', 'PAYIR_API_KEY', ''),
            ('IDPay API Key', 'IDPAY_API_KEY', ''),
            ('Admin IDs (comma-separated)', 'ADMIN_IDS', ''),
            ('Web Host', 'WEB_HOST', '0.0.0.0'),
            ('Web Port', 'WEB_PORT', '5000'),
            ('Database URL', 'DATABASE_URL', 'sqlite:///vpn_bot.db'),
            ('Secret Key (leave empty for auto)', 'SECRET_KEY', ''),
            ('Traffic Alert Threshold (GB)', 'TRAFFIC_ALERT_GB', '1'),
            ('Trial Duration (hours)', 'TRIAL_DURATION_HOURS', '2'),
            ('Trial Traffic Limit', 'TRIAL_TRAFFIC_LIMIT', '1'),
            ('Trial Traffic Unit', 'TRIAL_TRAFFIC_UNIT', 'GB'),
            ('Referral Commission %', 'REFERRAL_COMMISSION_PERCENT', '10')
        ]
        self.values = {field[1]: field[2] for field in self.fields}

    def draw_menu(self):
        self.stdscr.clear()
        height, width = self.stdscr.getmaxyx()

        # Title
        title = "🚀 VPN Bot Installer"
        self.stdscr.addstr(1, (width - len(title)) // 2, title, curses.A_BOLD)

        # Instructions
        instructions = "Use ↑↓ to navigate, Enter to edit, Tab to save and continue"
        self.stdscr.addstr(3, (width - len(instructions)) // 2, instructions)

        # Fields
        start_y = 5
        for i, (label, key, default) in enumerate(self.fields):
            y = start_y + i
            if y >= height - 2:
                break

            if i == self.current_field:
                self.stdscr.addstr(y, 2, f"▶ {label}: ", curses.A_BOLD)
                value = self.values[key] or "[empty]"
                self.stdscr.addstr(y, 2 + len(f"▶ {label}: "), value, curses.A_REVERSE)
            else:
                self.stdscr.addstr(y, 2, f"  {label}: {self.values[key] or '[empty]'}")

        # Footer
        footer = "Press 'q' to quit, 's' to save config, 'r' to run bot"
        self.stdscr.addstr(height - 1, (width - len(footer)) // 2, footer)

        self.stdscr.refresh()

    def edit_field(self):
        field_label, field_key, default = self.fields[self.current_field]
        height, width = self.stdscr.getmaxyx()

        # Create input window
        input_win = curses.newwin(3, width - 4, height // 2 - 1, 2)
        input_win.box()
        input_win.addstr(0, 2, f"Edit {field_label}")
        input_win.addstr(1, 2, "Value: ")
        input_win.refresh()

        # Get input
        curses.echo()
        value = input_win.getstr(1, 9, width - 13).decode('utf-8')
        curses.noecho()

        if value.strip():
            self.values[field_key] = value.strip()

    def save_config(self):
        """Save configuration to .env file"""
        env_path = Path('.env')
        with open(env_path, 'w') as f:
            f.write("# VPN Bot Configuration\n")
            f.write("# Generated by TUI Installer\n\n")
            for key, value in self.values.items():
                if value:
                    f.write(f"{key}={value}\n")

        return f"Configuration saved to {env_path}"

    def install_dependencies(self):
        """Install Python dependencies"""
        try:
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-r', 'requirements.txt'])
            return "Dependencies installed successfully"
        except subprocess.CalledProcessError as e:
            return f"Failed to install dependencies: {e}"

    def run_bot(self):
        """Start the bot"""
        try:
            os.chdir('src')
            subprocess.Popen([sys.executable, 'main.py'])
            return "Bot started successfully"
        except Exception as e:
            return f"Failed to start bot: {e}"

    def main(self, stdscr):
        self.stdscr = stdscr
        curses.curs_set(0)

        while True:
            self.draw_menu()
            key = self.stdscr.getch()

            if key == curses.KEY_UP:
                self.current_field = max(0, self.current_field - 1)
            elif key == curses.KEY_DOWN:
                self.current_field = min(len(self.fields) - 1, self.current_field + 1)
            elif key == ord('\n') or key == ord('\t'):  # Enter or Tab
                self.edit_field()
            elif key == ord('s'):
                message = self.save_config()
                self.show_message(message)
            elif key == ord('i'):
                message = self.install_dependencies()
                self.show_message(message)
            elif key == ord('r'):
                message = self.run_bot()
                self.show_message(message)
            elif key == ord('q'):
                break

    def show_message(self, message):
        height, width = self.stdscr.getmaxyx()
        msg_win = curses.newwin(5, width - 4, height // 2 - 2, 2)
        msg_win.box()
        msg_win.addstr(1, 2, "Message")
        msg_win.addstr(2, 2, message[:width - 8])
        msg_win.addstr(3, 2, "Press any key to continue...")
        msg_win.refresh()
        msg_win.getch()

def main():
    if len(sys.argv) > 1 and sys.argv[1] == '--help':
        print("VPN Bot TUI Installer")
        print("Usage: python install.py")
        print("Controls:")
        print("  ↑↓ - Navigate fields")
        print("  Enter - Edit field")
        print("  s - Save configuration")
        print("  i - Install dependencies")
        print("  r - Run bot")
        print("  q - Quit")
        return

    installer = Installer()
    curses.wrapper(installer.main)

if __name__ == '__main__':
    main()